doc-warnings: yes
test-warnings: no
strictness: medium
max-line-length: 80
# uses:
#     - flask
autodetect: yes
requirements:
    - setup.py
# ignore-paths:
#     - docs
#     - sample
ignore-patterns:
    - .*__init__.py
python-targets:
    - 3